name: 'weather_openweatherAPI_pipeline'
version: '1.0.0'
config-version: 2

profile: 'weather_pipeline'

# Define model paths and materializations
model-paths: ["models"]
seed-paths: ["seeds"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  weather_openweatherAPI_pipeline:
    bronze:
      +materialized: table
    silver:
      +materialized: table