weather_pipeline:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: weather_admin
      password: weather_password
      port: 5432
      dbname: weather_db
      schema: public
      threads: 4
